services:
  - type: web
    name: project-parva
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PARVA_ENABLE_EXPERIMENTAL_API
        value: "false"
      - key: PARVA_ENV
        value: production
      - key: PARVA_SERVE_FRONTEND
        value: "true"
      - key: CORS_ALLOW_ORIGINS
        value: https://project-parva.onrender.com
